server:
  port: 9090
   
spring:
   application:
       name: auxlate-spring-gateway
   cloud:
       gateway:
           routes:
            - id: CUSTOMER-SERVICE
              uri: http://localhost:8093/
              predicates:
               - Path=/custom/**
            - id: AEXLATE-CUSTOMER-SERVICE
              #uri: http://localhost:8765/
              uri: ld://AEXLATE-CUSTOMER-SERVICE/
              predicates:
               - Path=/cccc/**
           discovery:
              locator:
                 enabled: true
                 lower-case-service-id: true
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
